export {
  createAuditContext,
  buildFileMetadata,
  type CreateAuditContextOptions,
} from './context.js';
export {
  DEFAULT_AUDIT_CONFIG,
  DEFAULT_CONFIG_MAX_BYTES,
  SHERPA_CONFIG_FILE_NAME,
  loadAuditConfig,
  resolveAuditConfig,
  type AuditConfigIssue,
  type AuditConfigIssueCode,
  type AuditConfigIssueSeverity,
  type AuditConfigLoadResult,
  type LoadAuditConfigOptions,
  type SherpaJsonAuditConfig,
  type SherpaJsonConfig,
} from './config.js';
export {
  AuditEngine,
  runAudit,
  type AuditEngineOptions,
  type AuditEngineRunInput,
} from './engine.js';
export {
  AuditRuleRegistry,
  createAuditRuleRegistry,
  normalizeAuditRules,
  type RegisteredAuditRule,
} from './registry.js';
export {
  AUDIT_BASELINE_SCORE,
  AUDIT_MAX_SCORE,
  AUDIT_MIN_SCORE,
  DEFAULT_SEVERITY_WEIGHTS,
  calculateAuditScore,
  summarizeAudit,
  type AuditScoreOptions,
  type AuditScoreResult,
} from './scoring.js';
export {
  parseErrorRule,
  parseWarningRule,
  parseProblemRules,
  TOKEN_BUDGET_OVERRUN_RULE_ID,
  tokenBudgetOverrunRule,
  CONFLICTING_DIRECTIVES_RULE_ID,
  conflictingDirectivesRule,
  VAGUE_DIRECTIVES_RULE_ID,
  vagueDirectivesRule,
  MISSING_STACK_CONTEXT_RULE_ID,
  missingStackContextRule,
  CROSS_FILE_CONTRADICTIONS_RULE_ID,
  crossFileContradictionsRule,
  DUPLICATE_SECTIONS_RULE_ID,
  duplicateSectionsRule,
  OUTDATED_TOOL_REFERENCES_RULE_ID,
  outdatedToolReferencesRule,
  MISSING_PRIORITY_SIGNALS_RULE_ID,
  missingPrioritySignalsRule,
  VERBOSE_PREAMBLE_RULE_ID,
  verbosePreambleRule,
  UNBALANCED_SECTIONS_RULE_ID,
  unbalancedSectionsRule,
  MISSING_EXAMPLES_RULE_ID,
  missingExamplesRule,
  AMBIGUOUS_INSTRUCTIONS_RULE_ID,
  ambiguousInstructionsRule,
  heuristicAuditRules,
  defaultAuditRules,
} from './rules/index.js';
export type {
  AuditContext,
  AuditFileMetadata,
  AuditRule,
  AuditRuleCheckResult,
  AuditRuleCheckReturn,
  AuditRuleModule,
  AuditRuleRecommendationInput,
  AuditRuleSeverity,
  AuditRuleViolationInput,
  ResolvedAuditConfig,
} from './types.js';
